### ISSUE TITLE
Provide a link to an uploaded version of the extension

### ISSUE THREAD

**Issue by torinmr** [model-zoo/shift-ctrl-f#3]
Hey, this is a really great idea, thanks for working on it and sharing it!

It'd be great to have a link in the README to an already uploaded version of the extension, so there's an easy way to try it out without building and loading it yourself. (Especially since the build process doesn't work out of the box without installing a few dependencies.)

**Comment by cbuctok** [comment]
Also could you please provide the list of the requered dependencies?

**Comment by yoavz** [comment]
Good idea. I'm going to submit this to the Chrome web store today. Will update this ticket if it gets accepted.

**Comment by chagai95** [comment]
Thanks Yoav, love this!

**Comment by yoavz** [comment]
> Also could you please provide the list of the requered dependencies?

Just added in cb96f9e

**Comment by yoavz** [comment]
Happy to announce google has accepted this extension: https://chrome.google.com/webstore/detail/shift-ctrl-f-semantic-sea/alnafbdjkoiljlomnbcknehahbjoiped. I've added a link to the README in 4b742352e61a0a03179ce7c44b2973c662565aef
